### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by ksnsk** [SpaceAfterYou/SoulWorker.PasswordExtractor#1]
After compiling with Visual Studio Code, where is the exe program and how to use .
The example image is not the same as after compilation.
If possible, can you provide the compiled exe.
Sorry for bad English, this is machine translation.

**Comment by sawich** [comment]
Hi. No problem, I don't speak enough English to communicate freely either.

Machine translation brings people together. :)

I don't know how to build this solution in Visual Studio Code.
I wrote it using Visual Studio 2022.
Theoretically, building in Visual Studio Code should work identically.

| The executable is located at the path | 
| --- |
| `SoulWorker.PasswordExtractor.Cli\bin\Debug\net6.0` |
| `SoulWorker.PasswordExtractor.Cli\bin\Release\net6.0` |
| Depending on the configuration you choose |

I've added an automatic build: https://github.com/SpaceAfterYou/SoulWorker.PasswordExtractor/releases

Also, some users have reported that the extractor does not work on some versions of the game.

**Comment by ksnsk** [comment]
Thank you!
Visual Studio Code compiles fine, but how to use it.
My system is Win10X64.
Steam Soulworker[Client]ver=1.8.36.3  
Whether I compiled it, or the exe you provided, it's these errors:

PS I:\sws\swpe> .\SoulWorker.PasswordExtractor.Cli.exe I:\sws\Steam\steamapps\common\Soulworker_TWN\SoulWorker.exe
Unhandled exception. System.ApplicationException: Not found
   at SoulWorker.PasswordExtractor.Parser.AddressesFrom(String path) in D:\a\SoulWorker.PasswordExtractor\SoulWorker.PasswordExtractor\SoulWorker.PasswordExtractor\Parser.cs:line 48
   at SoulWorker.PasswordExtractor.Extract.From(String path) in D:\a\SoulWorker.PasswordExtractor\SoulWorker.PasswordExtractor\SoulWorker.PasswordExtractor\Extract.cs:line 8
   at Program.<Main>$(String[] args) in D:\a\SoulWorker.PasswordExtractor\SoulWorker.PasswordExtractor\SoulWorker.PasswordExtractor.Cli\Program.cs:line 4
   at Program.<Main>(String[] args)

PS E:\Game\code\SoulWorker.PasswordExtractor\SoulWorker.PasswordExtractor.Cli\bin\Debug\net6.0> .\SoulWorker.PasswordExtractor.Cli.exe I:\sws\Steam\steamapps\common\Soulworker_TWN\SoulWorker.exe
Unhandled exception. System.ApplicationException: Not found
   at SoulWorker.PasswordExtractor.Parser.AddressesFrom(String path) in E:\Game\code\SoulWorker.PasswordExtractor\SoulWorker.PasswordExtractor\Parser.cs:line 48
   at SoulWorker.PasswordExtractor.Extract.From(String path) in E:\Game\code\SoulWorker.PasswordExtractor\SoulWorker.PasswordExtractor\Extract.cs:line 8
   at Program.<Main>$(String[] args) in E:\Game\code\SoulWorker.PasswordExtractor\SoulWorker.PasswordExtractor.Cli\Program.cs:line 4
   at Program.<Main>(String[] args)

Is this a usage error, or something else?

**Comment by sawich** [comment]
I've updated. You can try it.

**Comment by ksnsk** [comment]
I got it. This tool is to view and decrypt the dumped exe, not to generate the dumped exe. However, what I want to know is how the dumped exe (eg SoulWorker_dump_global_03_13_2022.exe) is obtained, or it can only be provided by you. Of course thank you very much for providing a very good project.

**Comment by sawich** [comment]
This is actually not a very easy task. In the future I'm considering writing a program to extract the password from the regular version of the game.

One guy did something similar.
This is his discord: https://discord.com/invite/H7jZpcVJhq

This is another server, there's a Korean chat room, maybe they can help you figure it out: https://discord.gg/Z9aJswkv

_To create a dump, you can start by exploring "ScyllaHide"_

**Comment by ksnsk** [comment]
That being the case, wait for your future projects.
Thank you very much for your patient answer.

**Comment by sawich** [comment]
Always a pleasure 🤙
